apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-admin-vs
spec:
  hosts:
  - flask-admin
  http:
  - route:
    - destination:
        host: flask-admin
        subset: prod
      weight: 100
    - destination:
        host: flask-admin
        subset: canary
      weight: 0
