namespace: default
resources:
- namespace.yaml
- gateway.yaml
- gateway-vs.yaml
- flask-admin-v1.yaml
- flask-admin-vs.yaml
- flask-admin-dr.yaml
- configmap.yaml
patchesStrategicMerge:
- healthcheck_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: myhub.mydocker.com/flask/flask-admin
  newName: myhub.mydocker.com/flask/flask-admin
  newTag: "0.6"
