"""empty message

Revision ID: 2cc93f27aad9
Revises: 5c96eafbb2cf
Create Date: 2020-06-06 21:41:29.785063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc93f27aad9'
down_revision = '5c96eafbb2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('public_ip', table_name='process')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('public_ip', 'process', ['public_ip'], unique=True)
    # ### end Alembic commands ###
