"""empty message

Revision ID: 39ce7aa4dc95
Revises: fb8884e72712
Create Date: 2020-06-30 10:54:55.232697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ce7aa4dc95'
down_revision = 'fb8884e72712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('env_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'env_name')
    # ### end Alembic commands ###
