"""empty message

Revision ID: 47f9e44d9f02
Revises: 824b3cad7c83
Create Date: 2020-06-21 09:57:14.875350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47f9e44d9f02'
down_revision = '824b3cad7c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('cluster_config', sa.Text(), nullable=True))
    op.add_column('cluster', sa.Column('cluster_name', sa.String(length=50), nullable=True))
    op.drop_index('name', table_name='cluster')
    op.create_unique_constraint(None, 'cluster', ['cluster_name'])
    op.drop_column('cluster', 'name')
    op.drop_column('cluster', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('config', mysql.TEXT(), nullable=True))
    op.add_column('cluster', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'cluster', type_='unique')
    op.create_index('name', 'cluster', ['name'], unique=True)
    op.drop_column('cluster', 'cluster_name')
    op.drop_column('cluster', 'cluster_config')
    # ### end Alembic commands ###
