"""empty message

Revision ID: 5787c68b4ed4
Revises: 47f9e44d9f02
Create Date: 2020-06-21 12:26:19.492108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5787c68b4ed4'
down_revision = '47f9e44d9f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'update_time')
    # ### end Alembic commands ###
