"""empty message

Revision ID: 5c96eafbb2cf
Revises: c118d38df6c0
Create Date: 2020-06-06 19:59:33.215728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c96eafbb2cf'
down_revision = 'c118d38df6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('process', sa.String(length=200), nullable=True, comment='安装进度'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process')
    # ### end Alembic commands ###
