"""empty message

Revision ID: a44954a3ed72
Revises: 2cc93f27aad9
Create Date: 2020-06-18 10:56:48.447147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44954a3ed72'
down_revision = '2cc93f27aad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('create_user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('cluster_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namespace')
    op.drop_table('env')
    op.drop_table('cluster')
    # ### end Alembic commands ###
