"""empty message

Revision ID: a8d1c49d8194
Revises: 5b754ccb7815
Create Date: 2020-06-03 22:46:18.984370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d1c49d8194'
down_revision = '5b754ccb7815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('ss_port', sa.Integer(), nullable=True),
    sa.Column('ss_pwd', sa.String(length=256), nullable=True),
    sa.Column('cipher', sa.String(length=256), nullable=True, comment='密码加密'),
    sa.Column('exception', sa.Text(), nullable=True, comment='异常信息'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_info')
    # ### end Alembic commands ###
