"""empty message

Revision ID: d662e3eb08e7
Revises: 39ce7aa4dc95
Create Date: 2020-06-30 10:57:21.314785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd662e3eb08e7'
down_revision = '39ce7aa4dc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'project', ['name'], unique=True)
    # ### end Alembic commands ###
