apiVersion: v1
kind: Service
metadata:
  name: flask-admin
  namespace: ms-prod
  labels:
    app: flask-admin
    service: flask-admin
spec:
  type: NodePort
  ports:
  - port: 8081
    name: http
  selector:
    app: flask-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-admin-sa
  labels:
    account: flask-admin