apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-tutorial-hpa
  namespace: ms-prod
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-tutorial-1.7
  targetCPUUtilizationPercentage: 70
